package class32;

public class ExceptionDemo1 {

    public static void main(String[] args) {// exceptions are error in run time 

        System.out.println("Line1");
        System.out.println("Line1");
        System.out.println("Line1");
        System.out.println("Line1");
        System.out.println("Line1");
        System.out.println("Line1");
        System.out.println(10/0);// ArithmeticException: / by zero
        System.out.println("Line1");
        System.out.println("Line1");
        System.out.println("Line1");
        System.out.println("Line1");
        System.out.println("Line1");
    }
}
